server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: analyzer-service
  datasource:
    url: ${ANALYZER_DB_URL}
    username: ${ANALYZER_DB_USERNAME}
    password: ${ANALYZER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
kafka:
  bootstrap-servers: ${KAFKA_SERVERS}
  consumer:
    group-id: analyzer-service-group
  topics:
    analysis-request: analysis-request
    analysis-response: analysis-response
app:
  github:
    token: ${GITHUB_TOKEN}
    base-url: https://api.github.com
    query: |
      query($username: String!, $after: String) {
        user(login: $username) {
          databaseId
          createdAt
          followers { totalCount }
          repositories(ownerAffiliations: OWNER, first: 100, after: $after) {
            totalCount
            nodes {
              stargazerCount
              forkCount
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
          contributionsCollection {
            totalCommitContributions
            restrictedContributionsCount
          }
        }
      }

analyzer:
  filter:
    max-inactivity-years: 2
    min-size-kb: 10

logging:
  level:
    ru.devanalyzer.analyzer_service: DEBUG
    org.springframework.kafka: INFO
