services:
  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d user_service_db"]
      interval: 10s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_service_db
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_GET_URL_VALIDITY: ${S3_GET_URL_VALIDITY}
      S3_PUT_URL_VALIDITY: ${S3_PUT_URL_VALIDITY}
      S3_ENDPOINT: ${S3_ENDPOINT}
    depends_on:
      postgres-user:
        condition: service_healthy

  postgres-analyzer:
    image: postgres:16
    environment:
      POSTGRES_DB: ${ANALYZER_DB_NAME}
      POSTGRES_USER: ${ANALYZER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ANALYZER_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_analyzer_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ANALYZER_DB_USERNAME} -d ${ANALYZER_DB_NAME}"]
      interval: 10s
      retries: 5

  analyzer-service:
    build: ./analyzer-service
    ports:
      - "8082:8082"
    environment:
      ANALYZER_DB_URL: jdbc:postgresql://postgres-analyzer:5432/${ANALYZER_DB_NAME}
      ANALYZER_DB_USERNAME: ${ANALYZER_DB_USERNAME}
      ANALYZER_DB_PASSWORD: ${ANALYZER_DB_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      postgres-analyzer:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      ANALYZER_SERVICE_URL: ${ANALYZER_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
    depends_on:
      - user-service

volumes:
  postgres_user_data:
  postgres_analyzer_data:
