spring:
  application:
    name: user-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_db
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    ru.devanalyzer.user_service: INFO

server:
  port: 8081